version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-docker-container
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-jpa-app-container
    depends_on:
      - mysql
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
